# configuration file used to run GMET ensemble estimation

author = "Guoqiang Tang"
version = "0.0.1"
name = "PyGMET for SHARP"
date = "2022-12"
affiliation = "NCAR CGD"


#[default_GMET]
## sets mode in regression code: 1 = analog downscaling (NOT supported), 2 = interpolation for ensemble forcing
#MODE = 2
## Start date of regression  YYYYMMDD
#START_DATE = "20170201"
## End date of regression  YYYYMMDD
#END_DATE = "20170215"
## The file containing the list of station sites to process
#SITE_LIST = "../inputs/CALI.screened_stn_list_slope.v3.csv"
## Give the primary variable (this needs redoing)
#SITE_VAR = "prcp"
## The Variable string used within each station timeseries file that identifies precipitation
#STATION_VAR = "prcp"
## Grid information, Used only in mode 2
#GRID_LIST = "../inputs/CALI.gridinfo.0625_v3.nc"
## Number of stations to consider for each grid point
#NUM_STATIONS = 35
## Initial Search Distance in km (expanded if need be)
#MAX_DISTANCE = 100.0
## Output file name
#OUTPUT_FILE = "../outputs/regress_ts.nwp.xv.nc"
## Controls whether or not to check for temperature data
#SITE_VAR_T = "T"
## Location of input station or grid data (without trailing "/")
#DATA_DIRECTORY = "../stndata"
## Start date of input station data (YYYYMMDD)
#STN_START_DATE = "20170201"
## End date of input station data (YYYYMMDD)
#STN_END_DATE = "20170228"
## Generate new station weights (TRUE/FALSE) versus read existing ones? Change for different NUM_STATIONS
#GEN_STA_WEIGHTS = false
## Name of station weight file
#STA_WEIGHT_NAME = "../outputs/station_weights.35stn.bin"
## Use station weighting in the regression (TRUE/FALSE)?
#USE_STN_WEIGHTS = true
#
##  --- Dynamic Predictor Usage Settings ---
## Number of dynamic predictors (=length(DYN_VAR_NAMES); 0 to ignore)
#N_DYN_PREDICTORS = 2
## Dynamic predictor var list (= x, y, z, ...)
#DYN_VAR_NAMES = "cube_root_prec_rate, tmp_2m"
## Dynamic precipitation var name, if precip is not used set 'DYN_PRCP_VAR_NAME = '
#DYN_PRCP_VAR_NAME = "cube_root_prec_rate"
## Dynamic predictor data file list
#DYN_INPUT_FILE_LIST = "../inputs/gridded_datafile_list.txt"
#
##  --- K-Fold cross-validation settings ---
## Number of kfold cross validation trials per grid point (0 for no cross-validation)
#KFOLD_TRIALS = 10


# station input data (Fortran GMET input format station)
input_stn_list = "/Users/guoqiang/Github/GMET/test_cases/cali2017/inputs/CALI.screened_stn_list_slope.v3.csv"
input_stn_path = "/Users/guoqiang/Github/GMET/test_cases/cali2017/stndata"

# domain gridded attributes (e.g., dem, lon, lat, slope)
infile_grid_domain = "/Users/guoqiang/Github/GMET/test_cases/cali2017/inputs/CALI.gridinfo.0625_v3.nc"

# parent output path
outpath_parent = "/Users/guoqiang/Research/PyGMET_testout"

# target period
date_start = "2017-02-01"
date_end = "2017-02-15"

# target output variables (currently, only prcp, tmean, trange)
target_vars = ['prcp', 'tmean', 'trange']

# Number of stations to consider for each target point
nearstn_min = 35  # nearby stations: minimum number
nearstn_max = 35  # nearby stations: maximum number

# first try this radius (km). if not enough, expand
try_radius = 10000

# Initial Search Distance in km (expanded if need be)
initial_distance = 100

# overwrite flags
overwrite_stninfo = false