# Some default settings

########################################################################################################################
# general settings
########################################################################################################################

# master seed: control all probabilistic process (e.g., probabilistic estimation, machine learning methods)
# a negative value means random generation without reproducibility
master_seed = 20230104

########################################################################################################################
# settings for gridded estimation using regression or machine learning methods
########################################################################################################################

############################## station/grid file dimension name
# the spatial dims of input stations
stn_lat_name = 'lat'
stn_lon_name = 'lon'

# the 2D spatial dims of the target grid domain
# note that target grid domain netcdf must have x/y dims, while lat and lon are 2D arrays
grid_lat_name = 'latitude'
grid_lon_name = 'longitude'
grid_mask_name = 'mask'

# the 2D spatial dims of dynamic predictor inputs
dynamic_grid_lat_name = 'lat'
dynamic_grid_lon_name = 'lon'

########################################################################################################################
# default settings
# they are as useful as the above settings but using their default values does not affect model run for any case
########################################################################################################################

# gridding methods: locally weighted regression and meachine learning methods.
# Sklearn module is used to support most functions: https://scikit-learn.org/stable/supervised_learning.html
# Locally weighted regression.
#   Two original methods are LWR:Linear and LWR:Logistic.
#   Sklearn-based methods support simple usage with "model.fit()" and "model.predict" or "model.predict_prob", in the format of LWR:linear_model.METHOD
#   Examples of METHOD are LinearRegression, LogisticRegression, Ridge, BayesianRidge, ARDRegression, Lasso, ElasticNet, Lars, etc
# Global regression using machine learnig methods:
#   Machine learning methods are supported by sklearn. Parametrs of methods supported by sklearn can be defined at the bottom of this configuration file (optional)
#   Examples: ensemble.RandomForestRegressor, ensemble.RandomForestClassifier, neural_network.MLPRegressor, neural_network.MLPClassifier, ensemble.GradientBoostingClassifier, ensemble.GradientBoostingRegressor
# The parameters of sklearn methods can be defined in the [sklearn] section
gridcore_continuous = 'LWR:Linear'
gridcore_classification = 'LWR:Logistic' # for probability of event
n_splits = 10 # only useful for machine learning methods. cross validation to generate uncertainty estimates.

# output random fields
output_randomfield = false

# Number of stations to consider for each target point. nearstn_min<=nearstn_max.
nearstn_min = 35  # nearby stations: minimum number
nearstn_max = 35  # nearby stations: maximum number

# first try this radius (km). if not enough, expand. Could be useful to reduce computation time for large domain search.
try_radius = 10000

# overwrite existing files
overwrite_stninfo = false
overwrite_station_cc = false
overwrite_weight = false
overwrite_cv_reg = false
overwrite_grid_reg = false
overwrite_ens = false
overwrite_spcorr = false

########################################################################################################################
# distance-based weight calculation
########################################################################################################################

initial_distance = 100 # Initial Search Distance in km (expanded if need be)

# Weight calculation formula. Only two variables/parameters are allowed in the formula
# dist: distance between points (km in the script)
# maxdist (optional): max(initial_distance, max(dist)+1), which is a parameter used in weight calculation
# 3 is the exponential factor and is the default parameter
weight_formula = '(1 - (dist / maxdist) ** 3) ** 3'


########################################################################################################################
# method-related settings
# default values can be directly used
########################################################################################################################

[transform]
# note: the name must be consistent with transform_vars
[transform.boxcox]
exp = 4

[sklearn]
# if no parameters are provided or if the section does not even exist, default parameters will be used.
# just provide the method name, no need to include the submodule name
[sklearn.RandomForestRegressor]
n_estimators = 500 # a example of RandomForestRegressor parameter
n_jobs = 5
[sklearn.RandomForestClassifier]
n_estimators = 500 # a example of RandomForestRegressor parameter
n_jobs = 5